const DISPLAY_ALERT = 'SHOW_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';

const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const LOGOUT_USER = 'LOGOUT_USER';

const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

const HANDLE_CHANGE = 'HANDLE_CHANGE';
const CLEAR_VALUES = 'CLEAR_VALUES';

const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN';
const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN';
const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';

const SET_EDIT_JOB = 'SET_EDIT_JOB';

const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';
const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';

const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN';
const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR';

const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN ';
const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS ';

const CLEAR_FILTERS = 'CLEAR_FILTERS ';

const CHANGE_PAGE = 'CHANGE_PAGE';

const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

export {
  DISPLAY_ALERT,
  CLEAR_ALERT,
  SETUP_USER_BEGIN,
  SETUP_USER_SUCCESS,
  SETUP_USER_ERROR,
  TOGGLE_SIDEBAR,
  LOGOUT_USER,
  UPDATE_USER_BEGIN,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_ERROR,
  HANDLE_CHANGE,
  CLEAR_VALUES,
  CREATE_JOB_BEGIN,
  CREATE_JOB_SUCCESS,
  CREATE_JOB_ERROR,
  GET_JOBS_BEGIN,
  GET_JOBS_SUCCESS,
  SET_EDIT_JOB,
  DELETE_JOB_BEGIN,
  DELETE_JOB_ERROR,
  EDIT_JOB_BEGIN,
  EDIT_JOB_SUCCESS,
  EDIT_JOB_ERROR,
  SHOW_STATS_BEGIN,
  SHOW_STATS_SUCCESS,
  CLEAR_FILTERS,
  CHANGE_PAGE,
  GET_CURRENT_USER_BEGIN,
  GET_CURRENT_USER_SUCCESS,
};
